# 应用基础配置
server:
  port: 8080

# 日志配置（中文友好）
logging:
  level:
    io.github.iweidujiang.industry: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Redis 配置（连接本地 Docker 容器）
spring:
  data:
    redis:
      host: redis          # Docker Compose 服务名
#      host: localhost
      port: 6379
      password: devRed1s
      timeout: 2000ms

# 禁用 Spring Boot Banner
spring.main.banner-mode: off